name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bloc_concurrency: ^0.2.5
  dart_code_metrics: ^5.7.6
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  go_router: ^14.2.8
  injectable: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.4.0
  lottie: ^3.0.0
  mocktail: ^1.0.4
  retrofit: ^4.4.1
  stream_transform: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  injectable_generator: ^2.4.2
  json_serializable: ^6.8.0
  retrofit_generator: ^8.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/image/
    - assets/lottie/
    - assets/svg/
